# Generated by Django 3.1.4 on 2020-12-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201209_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='must_read',
            field=models.BooleanField(default=False),
        ),
    ]
